# Generated by Django 2.0 on 2018-02-02 08:33

from django.db import migrations, models
import django.utils.timezone
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180202_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to=service.models.video_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=service.models.image_directory_path),
        ),
    ]
