# Generated by Django 2.0 on 2018-02-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20180202_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tags', to='service.Image')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tags', to='service.Video')),
            ],
        ),
        migrations.CreateModel(
            name='TextTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('size', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_tags', to='service.Video')),
            ],
        ),
    ]
